"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Anchor, ArrowLeft, CheckCircle2, FileWarning, Landmark, Plus, ShieldCheck, Users } from "lucide-react";
import { findRecommendationRisk, sha256 } from "@/lib/compliance";
import { useStewardlane } from "@/lib/store";
import type { AuditEvent, CommentaryDraft, Household, Role } from "@/lib/types";

const uid = () => crypto.randomUUID();
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function Workspace() {
  const store = useStewardlane();
  const [view, setView] = useState<"households"|"drafts"|"audit">("households");
  const [selectedId, setSelectedId] = useState<string>();
  const selected = store.households.find((item) => item.id === selectedId) ?? store.households[0];
  const total = selected?.holdings.reduce((sum, holding) => sum + holding.marketValue, 0) ?? 0;
  const allocations = useMemo(() => selected ? Object.entries(selected.holdings.reduce<Record<string,number>>((map, holding) => ({...map,[holding.category]:(map[holding.category]??0)+holding.marketValue}),{})) : [], [selected]);

  return <main className="workspace"><aside className="sidebar"><Link href="/" className="wordmark lightmark">Stewardlane</Link><div className="identity"><label>Workspace role</label><select value={store.role} onChange={(event)=>store.setIdentity(event.target.value as Role, store.actor)}><option value="advisor">Advisor</option><option value="associate">Associate</option><option value="compliance">Compliance officer</option></select><input value={store.actor} onChange={(event)=>store.setIdentity(store.role,event.target.value)} aria-label="Team member name"/></div><nav><button className={view==="households"?"active":""} onClick={()=>setView("households")}><Users/>Households</button><button className={view==="drafts"?"active":""} onClick={()=>setView("drafts")}><FileWarning/>Review queue</button><button className={view==="audit"?"active":""} onClick={()=>setView("audit")}><ShieldCheck/>Audit ledger</button></nav><div className="sidebar-note"><span>Control boundary</span><p>AI output cannot become official commentary without a named advisor action.</p></div></aside>
  <section className="workarea"><header className="worktop"><div><p className="eyebrow">{view.replace("_"," ")}</p><h1>{view==="households"?"Household intelligence":view==="drafts"?"Advisor review queue":"Compliance evidence"}</h1></div><div className="role-pill">{store.role}</div></header>
  {view==="households" && <div className="dashboard-grid"><section className="panel households-panel"><div className="panel-head"><h2>Households</h2>{store.role!=="compliance"&&<AddHousehold/>}</div>{store.households.length===0?<EmptyHouseholds/>:<div className="household-list">{store.households.map((household)=><button key={household.id} className={selected?.id===household.id?"selected":""} onClick={()=>setSelectedId(household.id)}><span>{household.name}</span><small>{household.members.join(" Â· ")}</small></button>)}</div>}</section>
  <section className="panel detail-panel">{selected?<><div className="panel-head"><div><p className="eyebrow">Household record</p><h2>{selected.name}</h2></div>{store.role==="advisor"&&<DraftButton household={selected}/>}</div>{store.role==="associate"?<Restricted/>:<><div className="metric-row"><div><span>Recorded assets</span><b>{money.format(total)}</b></div><div><span>Holdings</span><b>{selected.holdings.length}</b></div><div><span>Risk profile</span><b>{selected.riskProfile||"Not recorded"}</b></div></div><h3>Allocation from recorded holdings</h3>{allocations.length?<div className="allocation">{allocations.map(([category,value])=><div key={category}><span>{category}</span><div><i style={{width:`${total?value/total*100:0}%`}}/></div><b>{total?Math.round(value/total*100):0}%</b></div>)}</div>:<p className="muted">No holdings entered. Stewardlane does not invent portfolio values.</p>}<div className="notes-grid"><div><span>Investment policy notes</span><p>{selected.policyNotes||"No notes recorded."}</p></div><div><span>Prior meeting notes</span><p>{selected.priorMeetingNotes||"No notes recorded."}</p></div></div></>}</>:<EmptyDetail/>}</section></div>}
  {view==="drafts"&&<DraftQueue/>}{view==="audit"&&<AuditLedger/>}</section></main>
}

function AddHousehold(){const add=useStewardlane((s)=>s.addHousehold);const [open,setOpen]=useState(false);return <>{<button className="small-button" onClick={()=>setOpen(true)}><Plus/>Add household</button>}{open&&<div className="modal"><form className="dialog" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);const values=String(data.get("holdings")||"").split("\n").map((line)=>line.trim()).filter(Boolean).map((line)=>{const [symbol,name,category,value,quantity]=line.split(",").map((item)=>item.trim());return {id:uid(),symbol,name:name||symbol,category:(category||"Equity") as Household["holdings"][number]["category"],marketValue:Number(value)||0,quantity:Number(quantity)||0}});add({id:uid(),name:String(data.get("name")),members:String(data.get("members")).split(",").map((v)=>v.trim()).filter(Boolean),riskProfile:String(data.get("risk")),policyNotes:String(data.get("policy")),recentActivity:String(data.get("activity")),priorMeetingNotes:String(data.get("notes")),holdings:values,createdAt:new Date().toISOString()});setOpen(false)}}><div className="dialog-head"><div><p className="eyebrow">New record</p><h2>Add household data</h2></div><button type="button" onClick={()=>setOpen(false)}>Close</button></div><label>Household name<input name="name" required/></label><label>Members, comma separated<input name="members" required/></label><div className="two"><label>Risk profile<input name="risk"/></label><label>Recent activity<input name="activity"/></label></div><label>Investment policy notes<textarea name="policy"/></label><label>Prior meeting notes<textarea name="notes"/></label><label>Holdings, one per line<textarea name="holdings" placeholder="VTI, Vanguard Total Stock Market, Equity, 125000, 480"/></label><p className="form-note">Format: symbol, name, category, market value, quantity. Nothing is prefilled or simulated.</p><button className="button gold" type="submit">Create household</button></form></div>}</>}

function DraftButton({household}:{household:Household}){const add=useStewardlane((s)=>s.addDraft);const actor=useStewardlane((s)=>s.actor);const [loading,setLoading]=useState(false);async function generate(){setLoading(true);try{const response=await fetch('/api/draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({household})});const data=await response.json();if(!response.ok)throw new Error(data.error);const id=uid(),createdAt=new Date().toISOString(),hash=await sha256(data.draft);const draft:CommentaryDraft={id,householdId:household.id,kind:'meeting_prep',original:data.draft,reviewed:data.draft,status:'review_required',createdAt};add(draft,{id:uid(),draftId:id,householdId:household.id,action:'created',actor,timestamp:createdAt,contentHash:hash})}catch(error){alert(error instanceof Error?error.message:'Drafting failed')}finally{setLoading(false)}}return <button className="small-button" onClick={generate} disabled={loading||household.holdings.length===0}>{loading?'Draftingâ€¦':'Generate grounded brief'}</button>}

function DraftQueue(){const {drafts,households,role,actor,reviewDraft}=useStewardlane();if(!drafts.length)return <Empty title="No drafts waiting" copy="Generate a brief from a household with recorded holdings. Every result will arrive here in review-required state."/>;return <div className="draft-stack">{drafts.map((draft)=>{const household=households.find((item)=>item.id===draft.householdId);return <article className="draft-card" key={draft.id}><div className="draft-banner"><span>AI draft</span><b>{draft.status.replace('_',' ')}</b></div><div className="draft-meta"><span>{household?.name}</span><time>{new Date(draft.createdAt).toLocaleString()}</time></div><ReviewEditor draft={draft} canReview={role==='advisor'} actor={actor} reviewDraft={reviewDraft}/></article>})}</div>}

function ReviewEditor({draft,canReview,actor,reviewDraft}:{draft:CommentaryDraft;canReview:boolean;actor:string;reviewDraft:ReturnType<typeof useStewardlane.getState>["reviewDraft"]}){const [text,setText]=useState(draft.reviewed);const risks=findRecommendationRisk(text);async function decide(status:'approved'|'discarded'){if(status==='approved'&&risks.length){alert('Recommendation-like language must be removed before approval.');return}const timestamp=new Date().toISOString();reviewDraft(draft.id,status,text,{id:uid(),draftId:draft.id,householdId:draft.householdId,action:status,actor,timestamp,contentHash:await sha256(text)})}return <><textarea className="draft-editor" value={text} onChange={(event)=>setText(event.target.value)} disabled={!canReview||draft.status!=="review_required"}/>{risks.length>0&&<p className="risk"><FileWarning/>Recommendation-like phrasing detected. Approval is blocked until revised.</p>}<div className="draft-actions"><span>Original AI output remains preserved in the audit record.</span>{canReview&&draft.status==='review_required'&&<div><button onClick={()=>decide('discarded')}>Discard</button><button className="approve" onClick={()=>decide('approved')}>Approve as advisor</button></div>}</div></>}

function AuditLedger(){const {audit,drafts,households,addAudit,actor}=useStewardlane();async function anchor(event:AuditEvent){const response=await fetch('/api/anchor',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({hash:event.contentHash})});const data=await response.json();if(!response.ok){alert(data.error);return}addAudit({id:uid(),draftId:event.draftId,householdId:event.householdId,action:'anchored',actor,timestamp:new Date().toISOString(),contentHash:event.contentHash,transactionSignature:data.signature})}return audit.length?<div className="audit-list">{audit.map((event)=><article key={event.id}><div className="audit-icon">{event.action==='anchored'?<Landmark/>:<CheckCircle2/>}</div><div><b>{event.action}</b><span>{households.find((item)=>item.id===event.householdId)?.name} Â· {event.actor}</span><code>{event.contentHash.slice(0,22)}â€¦</code>{event.transactionSignature&&<a target="_blank" rel="noreferrer" href={`https://explorer.solana.com/tx/${event.transactionSignature}?cluster=devnet`}>View devnet proof</a>}</div><time>{new Date(event.timestamp).toLocaleString()}</time>{event.action==='approved'&&!audit.some((item)=>item.action==='anchored'&&item.contentHash===event.contentHash)&&<button onClick={()=>anchor(event)}><Anchor/>Anchor hash</button>}</article>)}</div>:<Empty title="No audit events" copy="Draft creation, approval, discard, and optional devnet anchoring appear here automatically."/>}

function EmptyHouseholds(){return <Empty title="No household records" copy="Add real household and holdings data to begin. This workspace intentionally ships without demo portfolio values."/>}function EmptyDetail(){return <Empty title="Select a household" copy="Portfolio allocation and meeting context appear only after a record exists."/>}function Restricted(){return <div className="restricted"><ShieldCheck/><h3>Holdings access restricted</h3><p>Associates can schedule and manage relationship operations, but this MVP denies full portfolio detail by role.</p></div>}function Empty({title,copy}:{title:string;copy:string}){return <div className="empty"><div/><h2>{title}</h2><p>{copy}</p></div>}
